apiVersion: v1
kind: Service
metadata:
  name: LoadBalancer
spec:
  selector:
    app.kubernetes.io/name: scale-spring-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
